name: kollections
description: Port of Kotlin collection extensions.
version: 0.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
